name: updatedata

on: workflow_dispatch

jobs:
  updatedata:
    name: Update data
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python using Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
        shell: bash -l {0}
      - name: Download data from google drive
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          FILE_ID: ${{ secrets.FILE_ID }}
        run: |
          python tools/download_from_drive.py --token "$TOKEN" --refresh_token "$REFRESH_TOKEN" --client_id "$CLIENT_ID" --client_secret "$CLIENT_SECRET" --file_id "$FILE_ID" --output_path "./test.csv"
        shell: bash -l {0}
      - name: Make changes to pull request
        run: date +%s > report.txt
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update data
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update_data
          delete-branch: true
          title: '[Test] Create PR'
          body: |
            Create PR
            - Auto-generated PR in action
            - Create test.csv
          labels: |
            test
            automated pr
          assignees: pz-white
          reviewers: pz-white
          milestone: 1
          draft: false
