name: updatedata

on: workflow_dispatch

jobs:
  updatedata:
    name: Update data
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python using Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda activate test
          pip3 install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
        shell: bash -l {0}
      - name: Download data from google drive
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          FILE_ID: ${{ secrets.FILE_ID }}
        run: |
          python3 tools/download_from_drive.py --token $TOKEN --refresh_token $REFRESH_TOKEN --client_id $CLIENT_ID --client_secret $CLIENT_SECRET --file_id $FILE_ID --output_path "./test.csv"
